/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sslproxy_jni_CudaKernels */

#ifndef _Included_com_sslproxy_jni_CudaKernels
#define _Included_com_sslproxy_jni_CudaKernels
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sslproxy_jni_CudaKernels
 * Method:    decrypt
 * Signature: (I[[I[[I[[I[[I[[I[[I[[I[[I[[I[[I[[I[[I[[I[[I[[II)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_sslproxy_jni_CudaKernels_decrypt
  (JNIEnv *, jobject, jint, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
